Fix for #1430 by first testing to see if Item2 of the Tuple is null
xunit/assert.xunit pull request #22
Opened 2017-11-22 23:06 UTC by nickdevore

2017-11-22 23:06 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-11-23 02:09 UTC, bradwilson requested changes

2017-11-23 02:09 UTC, bradwilson commented on Sdk/Exceptions/AllException.cs
> +                                         error.Item2 == null ? "null" : error.Item2.ToString().Replace(Environment.NewLine, spaces),
This should just be a null or empty string, not the word `null`.

2017-11-27 17:02 UTC, dnfclas commented
__@nickdevore__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, .NET Foundation Pull Request Bot_

2017-11-28 06:32 UTC, bradwilson commented on Sdk/Exceptions/AllException.cs
> +                                         error.Item2?.ToString().Replace(Environment.NewLine, spaces),
I think you need `.Item2?.ToString()?.Replace` because calling .Replace on null will null-ref.

2017-11-28 16:19 UTC, nickdevore commented
@bradwilson I made the change you asked for, though I did have a null in that spot in the unit test, and it didn't throw the null reference exception.  Perhaps [my test](https://github.com/xunit/xunit/pull/1582/commits/6627a5091aa1253f64c4f0dbb2ed35a0d942886f) doesn't cover the scenario you're talking about?

2017-12-29 17:44 UTC, nickdevore commented
@bradwilson Just following up on this to make sure I did all that you wanted me to do on it.

2017-12-29 18:11 UTC, bradwilson commented
Sorry, haven't been doing much xUnit.net work over the holidays. I will come back to this soon!

2018-01-01 02:29 UTC, merged

2018-01-01 02:29 UTC, bradwilson commented
Thanks!